---
- name: blahblahblah
  hosts: web
  #gather_facts: no
  #become: true
  #vars_files:
  #  - vars/password

  tasks:
  - name: get the username
    debug:
      msg: The username is "{{username}}" and password is "{{password}}"
