- name: Build custom requirements.txt
  hosts: localhost
  connection: local
  gather_facts: no 

  tasks: 
  - name: Import requirements.yml to use collections list
    include_vars: requirements.yml

  - name: Add contents of each collections python dependencies to requirements.txt
    lineinfile:
      path: requirements.txt
      line: "{{ lookup('file', req_path) | replace(ee, gt) }}"
      create: yes
    loop: "{{ collection_paths }}"
    vars: 
      collection_paths: "{{ collections | product(['.txt']) | map('join') | list }}"
      req_path: "./collection_requirements/{{ item }}"
      ee: '=='
      gt: '<='