---
## have to login with podman to get to registry.redhat.io
version: 2

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

#ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  #system: bindep.txt

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest
  builder_image:
    #name: my-mirror.example.com/aap-mirror/ansible-builder-rhel8:latest
    name: registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:latest
    #signature_original_name: registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:latest
